<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="yanal" name="maven.CalculatorAppTest" tests="13" failures="1" timestamp="08 Jul 2018 09:22:52 GMT" time="0.039" errors="0">
  <testcase name="subtractTwoNumberSecondNumberTheBiggest" time="0.003" classname="maven.CalculatorAppTest"/>
  <testcase name="enterEquationWithError" time="0.001" classname="maven.CalculatorAppTest"/>
  <testcase name="enterDoubleEqualSign" time="0.001" classname="maven.CalculatorAppTest"/>
  <testcase name="subtractTwoNumber" time="0.004" classname="maven.CalculatorAppTest">
    <failure type="java.lang.AssertionError" message="Subtract two number (10-3) expected [3.0] but found [2.0]">
      <![CDATA[java.lang.AssertionError: Subtract two number (10-3) expected [3.0] but found [2.0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at maven.CalculatorAppTest.subtractTwoNumber(CalculatorAppTest.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- subtractTwoNumber -->
  <testcase name="addTwoNumber" time="0.007" classname="maven.CalculatorAppTest"/>
  <testcase name="enterEquationWithoutNumber" time="0.005" classname="maven.CalculatorAppTest"/>
  <testcase name="enterDoubleOpretor" time="0.001" classname="maven.CalculatorAppTest"/>
  <testcase name="divideTwoNumber" time="0.001" classname="maven.CalculatorAppTest"/>
  <testcase name="divideOddByEven" time="0.001" classname="maven.CalculatorAppTest"/>
  <testcase name="multiplyTwoNumber" time="0.003" classname="maven.CalculatorAppTest"/>
  <testcase name="enterOneOpretor" time="0.004" classname="maven.CalculatorAppTest"/>
  <testcase name="divideByZero" time="0.002" classname="maven.CalculatorAppTest"/>
  <testcase name="enterNumber" time="0.006" classname="maven.CalculatorAppTest"/>
</testsuite> <!-- maven.CalculatorAppTest -->
